### ISSUE TITLE
Juno doesn't remember position of window after closing

### ISSUE THREAD

**Issue by nilshg** [one-more-minute/Julia-LT#134]
As mentioned in the gitter chat:
Juno will not remember its position on the screen when closing and restarting. I keep my editor on my secondary screen, and Lighttable used to re-open the window there after I closed it (which was nice, given that I use `:window.maximize` upon init, so moving the window is a bit of a pain). Now with standalone Juno, the window will always open centered on my primary screen.

**Comment by nilshg** [comment]
I think this is fixed? It's working for me now in the latest version.

**Comment by one-more-minute** [comment]
Ah yes, this was fixed in the Atom-Shell branch of LT a while back.
