### ISSUE TITLE
Incorrect floating point output, zeros after decimal point removed?

### ISSUE THREAD

**Issue by loganwilliams** [one-more-minute/Julia-LT#145]
Hello,

I've noticed a very strange bug in Juno's output for certain mathematical operations, as shown below.

![screen shot 2014-12-27 at 9 23 30 pm](https://cloud.githubusercontent.com/assets/823027/5563134/a3575992-8e0e-11e4-820a-36d65d252254.png)

Note that the first three results are completely incorrect. In all cases, one or two zeros after the decimal point have been removed from the output. Output from the same input in the Julia REPL:

```
julia> 1/0.95
1.0526315789473684

julia> 1/0.999
1.001001001001001

julia> 1/0.985
1.015228426395939
```

**Comment by dpo** [comment]
Works for me:

![screen shot 2015-01-04 at 19 49 47](https://cloud.githubusercontent.com/assets/38760/5608230/e6eb0360-944a-11e4-9e88-3164e3ede780.png)

````
> versioninfo()
Julia Version 0.3.3
Commit b24213b* (2014-11-23 20:19 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_AFFINITY SANDYBRIDGE)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
````

LightTable 0.7.2, binary version 0.8.4, Juno 0.9.

**Comment by one-more-minute** [comment]
Yup, the rounding code had some teething issues but that should be fixed now. Thanks for the report.
