### ISSUE TITLE
why my icon is always running ?

### ISSUE THREAD

**Issue by songroom** [one-more-minute/Julia-LT#146]
i update julia from 0.3.3 to 0.3.4, but i find a bug that icon of  showing program running is always running whether julia has program run or not.
but it can run program normally besides this icon bug. thank you!

```
julia> versioninfo()
Julia Version 0.3.4
Commit 3392026* (2014-12-26 10:42 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Xeon(R) CPU E5-2630 v2 @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by toddleo** [comment]
I believe your observation is raised in #139 , pls also check on that.

**Comment by songroom** [comment]
use the "reset working indicator" command, it is ok! ,thank you very much!
