### ISSUE TITLE
Missing ``server`` method on binary install

### ISSUE THREAD

**Issue by joehuchette** [one-more-minute/Julia-LT#147]
Downloaded the binary from the website and I get the following when I try to execute a cell:
```
Couldn't connect to Julia

ERROR: `server` has no method matching server(::Int64, ::Int64, ::Bool)
 in server at /Users/huchette/.julia/v0.3/Jewel/src/Jewel.jl:16
 in include at /Applications/Juno.app/Contents/Resources/app/julia/lib/julia/sys.dylib
 in include_from_node1 at loading.jl:128
 in process_options at /Applications/Juno.app/Contents/Resources/app/julia/lib/julia/sys.dylib
 in _start at /Applications/Juno.app/Contents/Resources/app/julia/lib/julia/sys.dylib
while loading /Applications/Juno.app/Contents/Resources/app/plugins/Julia-LT/jl/init.jl, in expression starting on line 33
```

**Comment by one-more-minute** [comment]
Have you tried `Pkg.update()`?

**Comment by joehuchette** [comment]
Did it on v0.4, not v0.3 --- thanks!

**Comment by ArthurZ** [comment]
Pkg.update() did not help resolve ruining Juno in LightTable 
ERROR: `server` has no method matching server(::Int64, ::Int64, ::Bool)
 in server at C:\Users\...\.julia\v0.3\Jewel\src\Jewel.jl:16
 in include at boot.jl:245
 in include_from_node1 at loading.jl:128
 in process_options at client.jl:285
 in _start at client.jl:354
while loading C:\Users\...\AppData\Local\LightTable\plugins\Julia\jl\init.jl, in expression starting on line 33

**Comment by one-more-minute** [comment]
Did you get any errors when running Pkg.update()?

**Comment by SteveBronder** [comment]
I'm having the same issue. Nothing bad happens when I do Pkg.update()

julia> Pkg.update()
INFO: Updating METADATA...
INFO: Computing changes...
INFO: No packages to install, update or remove

Is there anything I can supply you with to help resolve this?
