### ISSUE TITLE
Code that evaluates to strings with color codes

### ISSUE THREAD

**Issue by dpo** [one-more-minute/Julia-LT#148]
I'm using [`Docile.jl`](https://github.com/MichaelHatherly/Docile.jl) and [`Lexicon.jl`](https://github.com/MichaelHatherly/Lexicon.jl) to document code and read documentation. All is well in the terminal and IJulia, but in LightTable, the color codes returned as part of documentation strings aren't interpreted. Perhaps those codes should be stripped out, or (better yet) processed. For now, a documentation string looks something like this:

![screen shot 2015-01-04 at 19 43 50](https://cloud.githubusercontent.com/assets/38760/5608210/0fd97942-944a-11e4-98d0-963664316224.png)

This came up as part of a [discussion on the `Lexicon` tracker](https://github.com/MichaelHatherly/Lexicon.jl/issues/20#issuecomment-68657048).

**Comment by MichaelHatherly** [comment]
This is likely to be a Lexicon problem rather than anything in Juno that should be fixed.

**Comment by one-more-minute** [comment]
Ok, in that case I'll close, but thanks for the report nonetheless.

@MichaelHatherly can of course let me know if there's anything I can do in Juno to improve the Docile/Lexicon experience, but I think everything should basically be there.

**Comment by MichaelHatherly** [comment]
@one-more-minute, yes it can be closed. Just needs sorting out of things on the Lexicon side.
