### ISSUE TITLE
node binary is incorrect in juno-linux-x64.zip

### ISSUE THREAD

**Issue by onurgu** [one-more-minute/Julia-LT#151]
I followed the instructions at http://junolab.org/docs/install.html

While it seems to work -I tried the tutorial-, I cannot see the console.

It prints

thread[stderr]:	
/home/onur/Desktop/projects/software/juno/linux64/resources/app/plugins/node/node: 1: /home/onur/Desktop/projects/software/juno/linux64/resources/app/plugins/node/node: Syntax error: "(" unexpected

![screenshot from 2015-01-11 21 02 04](https://cloud.githubusercontent.com/assets/56893/5696335/3f21c25a-99d5-11e4-95eb-2d9c89475956.png)

I suspect

$ file /home/onur/Desktop/projects/software/juno/linux64/resources/app/plugins/node/node
/home/onur/Desktop/projects/software/juno/linux64/resources/app/plugins/node/node: Mach-O 64-bit executable

node binary is mismatched.

How can I solve this?

**Comment by one-more-minute** [comment]
Ok, try downloading the LT binaries from here, and replace the node executable with the one from there. If that solves your issue I can update the bundles.

**Comment by onurgu** [comment]
After posting this issue, I downloaded LT and added Juno directly from their plugin list. That solved the problem. Is it the same as you wanted me to do? If it isn't, I can help by following your instructions.

**Comment by colintbowers** [comment]
I had the same issue, and solved it following the suggestion of @one-more-minute, that is, I just replaced the Juno node executable with the LT node executable. Note, I did not need to install Juno from the plugin list. Simply replacing the node executable was sufficient.

Cheers,

Colin

**Comment by ksmigiel** [comment]
I had exactly the same issue. Resolved as same as @colintbowers.

**Comment by madjestic** [comment]
I had the same issue, resolved it as suggested.  Can not the binary be fixed in the linux bundle?

**Comment by soruvok** [comment]
Had the same issue. Resolved as suggested by @one-more-minute.

**Comment by one-more-minute** [comment]
This should be fixed by the latest bundles, but let me know if it comes up again.
