### ISSUE TITLE
"Eval Move" menu entry has an extra space

### ISSUE THREAD

**Issue by samuela** [one-more-minute/Julia-LT#152]
`Evaluation > Eval(space)(space)Move` as opposed to `Evaluation > Eval(space)Block`. I'm using the Mac version.

**Comment by one-more-minute** [comment]
That's odd, seems to be because OS X doesn't support the `&` character. Any chance you could send a PR over [here](https://github.com/one-more-minute/Juno-LT/blob/efacda7e59b61857957f5ce6a63ea0c734952c8a/src/menu.cljs#L70) to get rid of it?

**Comment by samuela** [comment]
Ok, created https://github.com/one-more-minute/Juno-LT/pull/22.

**Comment by one-more-minute** [comment]
Cool, just merged.
