### ISSUE TITLE
PyPlot Crashes Julia

### ISSUE THREAD

**Issue by acheck10** [one-more-minute/Julia-LT#158]
When using PyPlot in Juno, I create multiple graphs (about 5 or so) at once.  When I close them one at a time, julia crashes and in the console, I get the error message: 

julia(36857,0x7fff727e4300) malloc: *** error for object 0x7fdcdd20a210: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug

signal (6): Abort trap: 6
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)

If I use close("all") to close them all at once, it usually works without crashing Julia the first time. However, if I generate a new plot, and then use close("all") again, julia crashes and I get the same error message.

**Comment by one-more-minute** [comment]
Have you tried this from the terminal REPL, and if so does it work better then?

**Comment by acheck10** [comment]
I just tried that. I am able to close all of the graphs from the REPL, but if I run the same program again, Julia crashes when creating them and I get the same exact error statement. Running IJulia in Safari seems to be the only stable way (at least on my system) to produce multiple plots using PyPlot.

**Comment by one-more-minute** [comment]
Ok, if you get the same issue from PyPlot it's an issue with that package – it'd be great if you could report it over at the [PyPlot repo](https://github.com/stevengj/PyPlot.jl).
