### ISSUE TITLE
ctrl-D in vim mode

### ISSUE THREAD

**Issue by bjarthur** [one-more-minute/Julia-LT#159]
ctrl-D in vim pages down, but in juno it shows the docs.  is there any reason not to use command-D on os x for docs?  not sure about windows.  would just like to resolve the conflict.

**Comment by one-more-minute** [comment]
Try adding `[:editor "ctrl-d" :editor.page-down]` to your user keymap, that should resolve it for you. If you still want docs access you can also add `[:editor "pmeta-d" :editor.doc.toggle]`.

**Comment by bjarthur** [comment]
thanks!  works like a charm.

for symmetry, i also added ```[:editor "pmeta-m" :editor.methods.toggle]```. 

the command key, as opposed to the control key, seems more 'mac-like' to me for these purposes, given that the D and M keys are not otherwise used.  is there a reason not to make this configuration the default?

**Comment by one-more-minute** [comment]
Possibly – I was really just going for consistency with Light Table, which uses `Ctrl-M` for docs by default. I'll think about changing it in future, anyway.
