### ISSUE TITLE
'x' on last character of line in Vim mode

### ISSUE THREAD

**Issue by bjarthur** [one-more-minute/Julia-LT#160]
it deletes it as it should, but it does not move the cursor to the left.

let me know if i should file an issue with the vim plugin maintainer.  if so, is there a way to test in light table from an existing juno installation?  ie, without installing a separate copy of light table?  thanks.

**Comment by one-more-minute** [comment]
Left a note about vim issues on #161, but re testing: You can open a plain text file with `Ctrl-T`, and Juno shouldn't have any affect on it, so you can use that to compare LT to plain CodeMirror.

**Comment by bjarthur** [comment]
```x``` on last character of line also does not work on [codemirror's demo](http://codemirror.net/demo/vim.html), so i opened an issue there.  thanks for the link.
