### ISSUE TITLE
Juno module syntax

### ISSUE THREAD

**Issue by meaningofshape** [one-more-minute/Julia-LT#165]
I am having trouble creating a Module in Juno (first time using Juno).  I keep getting the error "syntax: incomplete: premature end of input" after the first 'module xxx' line.

If the text is simply:
module MyModule
end

everything works fine.  As soon as I add anything in between, I get the error.  I greatly appreciate your attention as I imagine I am doing something silly.

**Comment by Varanas** [comment]
See [this](http://discuss.junolab.org/t/possible-issue-begin-end-out-of-date-results/91/4) discussion.
In short, something like
```
module MyModule
    function square(x) # note the indentation!
        x^2
    end
end
```
should work as well as 
```
module MyModule # don't eval here
function square(x) # eval here
    x^2                     # or here
end                        # or here
end                        # don't eval here
```
I guess it's a concious decision not to indent the contents of modules by default. Even though, it should probably be possible to evaluate the module itself and not get any errors.
