### ISSUE TITLE
Julia not loaded if JULIA_PKGDIR is set

### ISSUE THREAD

**Issue by peter1000** [one-more-minute/Julia-LT#172]
hi,
I have added an alternative PATH for pkg.

.bashrc
```
export JULIA_PKGDIR="/path/to/other/hdd/Data"
```

which means there is no `/home/username/.julia` folder.

*Couldn't connect to Julia*
*ERROR: Jewel not found ........*

I checked it and if I temporarly comment the `export line` install Juno it works even after I relogin with the alternate JULIA_PKGDIR.

`Pkg.dir()` in `Juno` points to  `/home/username/.julia` folder.
Where as `Pkg.dir()` in the terminal julia points to the correct exported path `/path/to/other/hdd/Data`

Seems to me this is somewhat of an error - just wanted to let you know.

Or maybe there is a way to add any Environment variables to LightTables - in such a case maybe it would be good to be included into the installation docs.

Arch Linux - julia used a binary nightly build.

Cheers
P

**Comment by one-more-minute** [comment]
This is probably due to the fact that Juno is launching Julia directly, as opposed to going through Bash. I recommend putting the line in your `.juliarc.jl`, e.g.

```jl
ENV["JULIA_PKGDIR"] = "..."
```
which should affect all Julia sessions.

**Comment by peter1000** [comment]
Thanks this works
