### ISSUE TITLE
Julia 0.4

### ISSUE THREAD

**Issue by meaningofshape** [one-more-minute/Julia-LT#174]
I would love to use the Interpolations.jl package, but it seems to requre Julia version 0.4.  Am I able to update my Juno to that version?  If so, would I loose any functionality from my current version?  What kinds of trouble could it cause?

**Comment by one-more-minute** [comment]
Sure, take a look at "Setting the Julia path" [here](http://junolab.org/docs/install-manual.html). If you have Julia 0.4 installed you just need to point Juno to it.

v0.4 support might be patchy at this stage but it should basically work.
