### ISSUE TITLE
Drag from the Special Characters menu

### ISSUE THREAD

**Issue by dpo** [one-more-minute/Julia-LT#175]
In many OSX applications, I'm able to drag special characters (from `Edit -> Special Characters...`) into the application. But in Juno, it doesn't work for me. Any idea why that could be? Is there another way to insert special characters (I often use ∇ and ‖)?

I can't try in "regular" LightTable, as that menu isn't available.

Thanks!

**Comment by dpo** [comment]
Ah, I think I can answer my question: I just discovered that I can type `\Vert` and `\bigtriangledown` (for some reason, `\nable` isn't available). Juno is awesome!

**Comment by dpo** [comment]
Here's an idea: how about LaTeX code in comments being rendered in Juno with Mathjax? That would be the bee's knees!

**Comment by one-more-minute** [comment]
I actually had a go at prototyping that a while back, and it's definitely doable. Might be a while before I have time to implement it properly though.

**Comment by dpo** [comment]
That would be the best!
