### ISSUE TITLE
Suggestion: Version Info

### ISSUE THREAD

**Issue by peter1000** [one-more-minute/Julia-LT#177]
I was trying to find out which version of juno I run.

I did not find anything from within juno looked in the downloaded bundle to find out.

BTW: I run the `Ubuntu/Debian bundle juno-linux-x64.zip` on Arch Linux: seems so far ok..

Maybe I missed it but it would be nice to have something like an **About** or a command like the one of Light Table.

searching for version one gets: `Light Table version 0.7.2`

---
On the same note: what I really miss under Edit is: somthing like: Find... / Replace...

Cheers

**Comment by Varanas** [comment]
You can check the version of the _plugin_ Juno in the Plugin Manager if that's what you're looking for.

**Comment by peter1000** [comment]
Thanks a lot, I got Juno 1.0.0 

but I noticed that the `version` in the extracted `juno-linux-x64.zip` says: v0.20.1

**Comment by Varanas** [comment]
That's the version of [atom-shell](https://github.com/atom/atom-shell), the underlying component that replaced node-webkit for LT-master and the custom Juno builds, if I'm not mistaken.
And yup, [Juno 1.0.0](https://github.com/one-more-minute/Juno-LT/releases/tag/1.0.0) is the most recent release.

**Comment by peter1000** [comment]
Thanks a lot.
