### ISSUE TITLE
Menus not visible

### ISSUE THREAD

**Issue by izahn** [one-more-minute/Julia-LT#189]
I downloaded the bundle from https://junolab.s3.amazonaws.com/release/1.0.0/juno-linux-x64.zip on my Arch Linux system and launched the Juno executable. Everything works, except that the menu font is not visible, as shown in this screen shot:
![junomenu](https://cloud.githubusercontent.com/assets/321235/7340215/242ded74-ec56-11e4-8cd6-5fcdb68625f9.png)

In the terminal I see this:
```
[11052:0426/205639:ERROR:browser_main_loop.cc(163)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
Fontconfig warning: FcPattern object size does not accept value 10(i)
[11077:0426/205640:INFO:renderer_main.cc(207)] Renderer process started
```

Any ideas what might be causing this? If there is additional debugging info I can provide please let me know.

**Comment by one-more-minute** [comment]
I can't test on Arch Linux, unfortunately, but what you could try is launching the [Electron](https://github.com/atom/electron) shell on its own. If that reproduces the problem they'll be able to help you with it.

**Comment by izahn** [comment]
I just tried on a fresh install on a VM and it worked fine. Seems to be something specific to my setup, so closing since I can't reproduce it.

**Comment by one-more-minute** [comment]
Fair enough. Honestly, you're not likely to ever need the menu anyway, since you can do all the same stuff through shortcuts and the command bar.
