### ISSUE TITLE
Unble to update Julia Plug in

### ISSUE THREAD

**Issue by ArthurZ** [one-more-minute/Julia-LT#192]
I have been unable to update the plug in in LightTable.
The earlier version loads with errors like
Failed to load resource: file:///C:/Users/AZ/AppData/Local/LightTable/plugins/Julia/css/browser.css etc.

Trying to update it produced
Error: EBUSY, resource busy or locked 'C:\Users\AZ\AppData\Local\LightTable\plugins\Julia\jl\init.jl'

**Comment by Varanas** [comment]
I'm pretty sure this is because you didn't kill the Julia process before updating. Simply type "kill" into the command pane and update afterwards. 
Note however that you may need to uninstall any residues of the Julia plug-in before trying again - at least that was the case for me.

**Comment by ArthurZ** [comment]
Hi Varanas,
Thank you for the reply, I confirm that it worked (just did not know I can issue the Kill command right in the command panel in LightTable).
I did not un-install the Julia plugin, instead went into update and it worked.
