### ISSUE TITLE
Introductory tutorial fails at line 88, Using Images, and again at line 129 convert (Image, scale(foo_grid(500), 1/80))

### ISSUE THREAD

**Issue by rcdenne** [one-more-minute/Julia-LT#208]
I'm a complete newbee with 10 minutes experience, having downloaded and installed the Juno+Julia bundle for Windows.  I'm running it on Win10, where everythng else in the intro tutorial ran as expected.  See screen shots attached.
![error01_20150824](https://cloud.githubusercontent.com/assets/4720232/9457105/fb262402-4aa4-11e5-953f-2b76229c95f8.png)
![error02_20150824](https://cloud.githubusercontent.com/assets/4720232/9457108/fee240a8-4aa4-11e5-938b-bf268a27721a.png)

**Comment by one-more-minute** [comment]
It looks like the `Pkg.add("Images")` step didn't run as expected (perhaps you just selected `Pkg` and evaluated that?). Try evaluating `Pkg.update()` followed by adding Images again, then `using Images` should work.

**Comment by rcdenne** [comment]
That solved it.  Thanks.  Sorry for the stupidity.  I’m looking forward to learning more about Julia, although getting over the de-vectorization issue will take some effort.

Thanks again,

Bob
