### ISSUE TITLE
Juno unresponsive, then unresponsive again, then couldn't connect to Julia, then seems to work but throws errors when I want to close the window.

### ISSUE THREAD

**Issue by mmagnuski** [one-more-minute/Julia-LT#219]
I followed the installtion steps (along with `Pkg.add("Jewel")` and `Pkg.update()`) but Julia was not responsive. "Spinning up Julia" would disappear after a while but the progress animation would not - and Juno was unresponsive. 
After updating LightTable (i had a pop-up saying I can update) the first time I started Juno - it would seem it had successfully connected to Julia, but it still remained unresponsive to me hitting ctrl+enter multiple times. When I was closing the window the following error appeared in Juno console:

```
Uncaught Error: read ECONNRESET
Uncaught object
[1] cljs.core.BitmapIndexedNode.inode_lookup
[10185] cljs.core.PersistentHashMap.cljs$core$ILookup$_lookup$arity$3
[2033]  c
[2046]  a
[10182] cljs.core.PersistentHashMap.cljs$core$ILookup$_lookup$arity$2
[2023]  b
[2044]  a
[3433]  b
[3448]  a
[5475]  cljs.core.Keyword.cljs$core$IFn$_invoke$arity$1
[20487] a
[20492] b
[21453] anonymous
[77]    emitOne
[166]   emit
[21]    ipc.sendSync
[110]   RemoteMemberFunction
[21285] c
[21291] a
(...)
```

Then, the part below is repeated multiple times (probably once for each of my ctrl-enter presses):

```
[21340] lt.objs.app.__BEH__close_BANG_
[6196]  c
[6236]  a
[20443] c
[20477] a
[20488] a
[20492] b
[21453] anonymous
[77]    emitOne
[166]   emit
[21]    ipc.sendSync
[110]   RemoteMemberFunction
[21285] c
[21291] a
```

Doesn't tell me much, but maybe there is some important mesage encoded in all this text :wink: 

Next time - after starting Juno I have the same story as before update - spinning up Julia disappears but the spinning animation does not and Juno is ignoring me completely. But this time when I want to close the window I got the "couldn't connect to Julia" message. I can't close the window however.
(but I had a previous window that generated the error I pasted before still open [couldn't close it normaly])

Then after forcing close of both Juno windows - Juno connects to Julia, but I can't execute the code. However, after opening a new tab - everything works!

When I try to close the Juno window I am getting the same error as before (the one I pasted above - with the repeated part). I can't close the window and have to ask windows to kill Juno (sorry :cry: ). This repeats every time I run Juno now (without the need to open a new tab, just the error when I try to close).

So it's not so bad, but I would prefer to close Juno with respect, without using force.
I would be happy to help debugging - if anybody could give me a hint on what to try.
Thanks!

**Comment by IvanPodvezanec** [comment]
I'm having exactly the same problem... :(
