### ISSUE TITLE
Trouble finding julia on OS-X

### ISSUE THREAD

**Issue by joehuchette** [one-more-minute/Julia-LT#94]
Following the instructions on your [great new page](http://junolab.org/docs/installing.html), after restarting I get a dialog box that says 

Couldn't connect to Julia
Could not find command: julia

The log output is:

```
bootstrap.js[17085]:     Error: spawn ENOENT true
bootstrap.js[17085]:     ERROR running:  julia
```

It looks like it's having trouble finding the julia executable, which is definitely on my path. I tried manually adding it to the Lighttable path as you mention in the troubleshooting section, but it didn't fix the problem. Any ideas? I've tried running Juno a handful of times in the past and always run into the same issue; I figure I'd actually stick with it this time to see if I can't resolve the issue.

**Comment by Sisyphuss** [comment]
I had the same problem. But I solved this problem suddenly. 
I ran Juno from the terminal. It detected that Jewel wasn't installed. So it installed it automatically. Julia connected. Problem solved!
